version: "3.9"
services:
  api:
    environment:
      - NAME_DB=postgres
      - HOST_DB=host.docker.internal
      - USER_DB=postgres
      - PW_DB=pass
      - PORT_DB=5432
      - HOST=0.0.0.0
      - PORT=8001
    build: api/.
    ports:
      - 8001:8001
  socket:
    environment:
      - NAME_DB=postgres
      - HOST_DB=host.docker.internal
      - USER_DB=postgres
      - PW_DB=pass
      - PORT_DB=5432
      - HOST=0.0.0.0
      - PORT=8000
      - BEARER=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsicHJvdmlzaW9uaW5nIiwicHJpdmF0ZToqIiwic2hhcmVkOioiXSwiaWF0IjoxNjg3ODIxNjk1LCJpc3MiOiJmcm9udCIsInN1YiI6IjMxZWIwY2E4MzdmNjFlMjA5NzI2IiwianRpIjoiNzM5NjZlYzhmMjY5YTRkNyJ9.2QBm0jYHpRk-P_o_M9z94Gqx3kWx15YP6eEl4v3Foho
      - CHANNEL=cha_dihw4
      - SECRET_KEY=test
    build: socket/.
    ports:
      - 8000:8000
